(()=>{(async()=>{try{const r=await fetch('./facet_policy.json',{cache:'no-store'});if(!r.ok)return;const p=await r.json(),f=p.facets||{},mr=p.market_regions||{};for(const [id,cfg] of Object.entries(f)){const el=document.getElementById(id);if(!el)continue;const wrap=el.closest('.f');if(wrap)wrap.style.display=cfg.visible===false?'none':''}const regionEl=document.getElementById('region'),countryEl=document.getElementById('country'),ageEl=document.getElementById('age');const regionCfg=f.region||{},countryCfg=f.country||{},ageCfg=f.age||{};const matureRegions=Array.isArray(regionCfg.values)?regionCfg.values:[];const matureCountries=Array.isArray(countryCfg.values)?countryCfg.values:[];if(regionEl){const vals=regionCfg.visible?['全世界',...matureRegions]:(matureRegions.length===1?matureRegions:['全世界']);regionEl.innerHTML=vals.map(v=>`<option>${v}</option>`).join('')}if(countryEl){const update=()=>{const rv=regionEl?.value||'全世界';const vals=rv==='全世界'?matureCountries:(Array.isArray(mr[rv])?mr[rv]:[]);countryEl.innerHTML='<option>全部</option>'+vals.map(v=>`<option>${v}</option>`).join('')};regionEl?.addEventListener('change',update);update()}if(ageEl){ageEl.innerHTML='<option>全部</option>'+(ageCfg.visible&&Array.isArray(ageCfg.values)?ageCfg.values.map(v=>`<option>${v}</option>`).join(''):'')}if(typeof render==='function')render()}catch(e){console.warn('facet policy unavailable; keeping fail-safe default UI')}})();})();

(()=>{
const HERO='https://images.unsplash.com/photo-1606197469884-00fba216f529?auto=format&fit=crop&fm=jpg&q=82&w=1800';
const STUDY='https://images.unsplash.com/photo-1759984782211-3a02ca78e6ac?auto=format&fit=crop&fm=jpg&q=78&w=1200';
const WEDDING='https://images.unsplash.com/photo-1677768062220-32f1658715c4?auto=format&fit=crop&fm=jpg&q=78&w=1200';
const SLEEP='https://images.unsplash.com/photo-1758273239288-9b60777397c5?auto=format&fit=crop&fm=jpg&q=78&w=1200';
const css=`
.hero{background-image:linear-gradient(90deg,rgba(19,24,24,.72),rgba(19,24,24,.28)),url('${HERO}')!important;background-size:cover!important;background-position:center 48%!important;}
.hero:before{display:none!important}.hero-copy{max-width:720px}.hero p{max-width:650px}.hero-search{backdrop-filter:blur(8px)}
.signal-visual{height:122px!important;background-size:cover!important;background-position:center!important}.signal-visual:after{display:none!important}
.signal-card{padding:14px!important;overflow:hidden}.signal-card h3{font-size:17px!important}.count{margin-top:2px}.tags{display:none!important}.card .pill{display:none!important}
#resonance .eyebrow{display:none!important}.res-card{background:rgba(255,255,255,.94)!important}
@media(max-width:620px){.hero{min-height:480px!important;background-position:center!important}.hero h1{font-size:42px!important;line-height:1.08!important}.signal-grid{display:flex!important;overflow-x:auto!important;scroll-snap-type:x mandatory;padding-bottom:8px}.signal-card{min-width:78vw!important;scroll-snap-align:start}.signal-visual{height:150px!important}.resonance-grid{display:grid!important;grid-template-columns:1fr!important}.card{padding:18px!important}}
`;
const style=document.createElement('style');style.dataset.humanSignalPresentation='v2';style.textContent=css;document.head.appendChild(style);
const res=document.getElementById('resonance');if(res){const h=res.querySelector('h2');if(h)h.textContent='有些生活，你可能也熟悉';const p=res.querySelector('.lead');if(p)p.textContent='不一定相同，但有些時刻會讓人想起自己的日子。';}
function photoFor(text=''){const s=String(text);if(/婚禮|結婚|婚姻/.test(s))return WEDDING;if(/睡|失眠|休息/.test(s))return SLEEP;if(/學習|教育|考試|學生/.test(s))return STUDY;return HERO;}
function apply(root=document){root.querySelectorAll?.('.signal-card').forEach(card=>{const visual=card.querySelector('.signal-visual');if(!visual)return;const title=card.querySelector('h3')?.textContent||'';visual.style.backgroundImage=`linear-gradient(0deg,rgba(28,24,20,.12),rgba(28,24,20,.02)),url('${photoFor(title)}')`;});root.querySelectorAll?.('.tags').forEach(x=>x.remove());}
const mo=new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes)if(n.nodeType===1)apply(n)});mo.observe(document.documentElement,{childList:true,subtree:true});apply();
})();
