(()=>{(async()=>{try{const r=await fetch('./facet_policy.json',{cache:'no-store'});if(!r.ok)return;const p=await r.json(),f=p.facets||{},mr=p.market_regions||{};for(const [id,cfg] of Object.entries(f)){const el=document.getElementById(id);if(!el)continue;const wrap=el.closest('.f');if(wrap)wrap.style.display=cfg.visible===false?'none':''}const regionEl=document.getElementById('region'),countryEl=document.getElementById('country'),ageEl=document.getElementById('age');const regionCfg=f.region||{},countryCfg=f.country||{},ageCfg=f.age||{};const matureRegions=Array.isArray(regionCfg.values)?regionCfg.values:[];const matureCountries=Array.isArray(countryCfg.values)?countryCfg.values:[];if(regionEl){const vals=regionCfg.visible?['全世界',...matureRegions]:(matureRegions.length===1?matureRegions:['全世界']);regionEl.innerHTML=vals.map(v=>`<option>${v}</option>`).join('')}if(countryEl){const update=()=>{const rv=regionEl?.value||'全世界';const vals=rv==='全世界'?matureCountries:(Array.isArray(mr[rv])?mr[rv]:[]);countryEl.innerHTML='<option>全部</option>'+vals.map(v=>`<option>${v}</option>`).join('')};regionEl?.addEventListener('change',update);update()}if(ageEl){ageEl.innerHTML='<option>全部</option>'+(ageCfg.visible&&Array.isArray(ageCfg.values)?ageCfg.values.map(v=>`<option>${v}</option>`).join(''):'')}}catch(e){console.warn('facet policy unavailable; keeping fail-safe default UI')}})()})();

(()=>{
const HERO='https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&fm=jpg&q=92&w=1800';
const ORDER=['work','sleep','home','relationship','city','money'];
const LABEL={work:'工作與職場',sleep:'睡眠與身心',home:'家庭與照顧',relationship:'關係與感情',city:'城市與生活',money:'生活與消費'};
const HINT={work:'職場・轉職・工作壓力',sleep:'失眠・焦慮・情緒',home:'育兒・家人・照顧',relationship:'戀愛・婚姻・相處',city:'搬家・生活適應・孤單',money:'金錢・物價・選擇'};
const IMAGES={
work:['https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&fm=jpg&q=86&w=1000','https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&fm=jpg&q=86&w=1000','https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&fm=jpg&q=86&w=1000'],
sleep:['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&fm=jpg&q=86&w=1000','https://images.unsplash.com/photo-1520206183501-b80df61043c2?auto=format&fit=crop&fm=jpg&q=86&w=1000','https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&fm=jpg&q=86&w=1000'],
home:['https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&fm=jpg&q=86&w=1000','https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&fm=jpg&q=86&w=1000','https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&fm=jpg&q=86&w=1000'],
relationship:['https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&fm=jpg&q=86&w=1000','https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&fm=jpg&q=86&w=1000','https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&fm=jpg&q=86&w=1000'],
city:['https://images.unsplash.com/photo-1444723121867-7a241cacace9?auto=format&fit=crop&fm=jpg&q=86&w=1000','https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&fm=jpg&q=86&w=1000','https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&fm=jpg&q=86&w=1000'],
money:['https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&fm=jpg&q=86&w=1000','https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&fm=jpg&q=86&w=1000','https://images.unsplash.com/photo-1565514020179-026b92b84bb6?auto=format&fit=crop&fm=jpg&q=86&w=1000']};
const INSIGHT={work:['努力工作的人，也常在學習怎麼安心休息','真正反覆出現的，不只是忙，而是工作如何進入休息、週末與自我評價。'],sleep:['有些疲憊，不是睡一覺就會消失','不同人的失眠背後，常連著壓力、情緒，以及很久沒有真正放鬆的生活。'],home:['照顧別人的人，也需要一個被照顧的位置','家庭裡的愛、疲累與愧疚可以同時存在；看見這些複雜感受，本身就是理解。'],relationship:['很多關係的難題，不是不在乎，而是不知道怎麼靠近','想被理解、又怕再次受傷，是許多人在親密關係裡共同出現的拉扯。'],city:['一個陌生地方，常從很小的熟悉感開始變成家','適應不是突然完成的，而是從認得一條路、一間店、一個會打招呼的人慢慢發生。'],money:['人們在意的往往不只是價格，而是生活還剩多少選擇','消費與物價背後，常連著安全感、尊嚴，以及能不能替自己保留一點喘息。']};
function clean(v=''){return String(v||'').replace(/\s+/g,' ').trim()}
function key(v=''){return clean(v).toLowerCase().replace(/[\s\p{P}\p{S}]+/gu,'')}
function scene(x){const s=clean([x?.topic,x?.title,x?.voice,x?.summary,x?.story,x?.context].join(' '));if(/工作|職場|上班|主管|同事|轉職|薪水|加班|career|job|work/i.test(s))return'work';if(/睡眠|失眠|睡不|焦慮|情緒|疲憊|壓力|sleep|anxiety/i.test(s))return'sleep';if(/家庭|家人|父母|媽媽|爸爸|孩子|育兒|照顧|family|parent/i.test(s))return'home';if(/感情|戀愛|婚姻|伴侶|朋友|分手|relationship|dating/i.test(s))return'relationship';if(/城市|搬家|租屋|通勤|鄰居|city|move/i.test(s))return'city';if(/消費|物價|金錢|存錢|預算|money|price/i.test(s))return'money';return''}
function data(){try{return Array.isArray(RAW)?RAW:[]}catch{return[]}}
function title(x){return clean(x?.title||x?.voice||'')}
function voice(x){const s=clean(x?.voice||'');if(!s||s===title(x))return'';return s.length>92?s.slice(0,90)+'…':s}
function pick(s,n=4){const out=[],seen=new Set();for(const x of data()){if(scene(x)!==s)continue;const k=key(title(x));if(!k||seen.has(k))continue;seen.add(k);out.push(x);if(out.length>=n)break}return out}
function image(s,i=0){const a=IMAGES[s]||[];return a[i%a.length]||''}
function esc(s){return clean(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function installStyle(){if(document.querySelector('[data-hs-v14]'))return;const st=document.createElement('style');st.dataset.hsV14='1';st.textContent=`body{background:linear-gradient(180deg,#fffdf8 0%,#fff8ee 50%,#fffdf9 100%)!important}.hero{min-height:520px!important;background-image:linear-gradient(90deg,rgba(64,38,20,.18),rgba(255,245,214,.03)),url('${HERO}')!important;background-size:cover!important;background-position:center 48%!important}.hero:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(49,31,20,.28) 0%,rgba(49,31,20,.06) 58%,rgba(255,222,158,.08));pointer-events:none}.hero-copy{z-index:2!important}.signal-card{overflow:hidden!important}.signal-visual{height:118px!important;background-size:cover!important;background-position:center!important}.resonance-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.hs14-card{display:grid;grid-template-columns:150px 1fr;overflow:hidden;padding:0!important;background:#fff!important}.hs14-photo{min-height:220px;background-size:cover;background-position:center}.hs14-copy{padding:20px}.hs14-kicker{font-size:12px;color:#a06d47;font-weight:800;margin-bottom:7px}.hs14-copy h3{font-size:21px;line-height:1.38;margin:0 0 8px}.hs14-copy p{font-size:13px;line-height:1.7;color:#675f57;margin:0}.hs14-voice{margin-top:12px;padding-top:10px;border-top:1px solid #eee3d8;font-size:13px;line-height:1.55;color:#4e4842}.hs14-voice:before{content:'“';color:#b67b50;font-size:18px;font-weight:800;margin-right:3px}.hs14-link{display:inline-block;margin-top:12px;color:#704e37;font-size:12px;font-weight:800;text-decoration:none}@media(max-width:620px){.hero{min-height:520px!important;background-position:58% center!important}.resonance-grid{grid-template-columns:1fr!important}.hs14-card{grid-template-columns:112px 1fr}.hs14-photo{min-height:235px}.hs14-copy{padding:16px}.hs14-copy h3{font-size:18px}.signal-card{min-width:44vw!important}}`;document.head.appendChild(st)}
function renderTopics(){const g=document.querySelector('#signalGrid');if(!g)return;g.innerHTML='';ORDER.forEach((s,i)=>{const items=pick(s,99),c=document.createElement('article');c.className='signal-card';c.innerHTML=`<div class="signal-visual" style="background-image:url('${image(s,i)}')"></div><h3>${LABEL[s]}</h3><p class="count">${items.length?items.length+' 個近期片段':'持續收集中'}</p><div class="hs-topic-hint">${HINT[s]}</div>`;c.onclick=()=>{try{exploreTopic(LABEL[s])}catch{document.querySelector('#explore')?.scrollIntoView({behavior:'smooth'})}};g.appendChild(c)})}
function renderInsights(){const g=document.querySelector('#resonanceGrid');if(!g)return;g.innerHTML='';let made=0;ORDER.forEach((s,si)=>{if(made>=4)return;const items=pick(s,3);if(!items.length)return;const [head,body]=INSIGHT[s],x=items[0],v=voice(x),href=x?.url||x?.source_url||'',c=document.createElement('article');c.className='hs-insight-card hs14-card';c.innerHTML=`<div class="hs14-photo" style="background-image:url('${image(s,si+1)}')"></div><div class="hs14-copy"><div class="hs14-kicker">從 ${items.length} 個不同生活片段裡，我們看見</div><h3>${esc(head)}</h3><p>${esc(body)}</p>${v?`<div class="hs14-voice">${esc(v)}</div>`:''}${href?`<a class="hs14-link" href="${esc(href)}" target="_blank" rel="noopener noreferrer">走進其中一個人的故事 →</a>`:''}</div>`;g.appendChild(c);made++})}
function dedupeExplore(){const cards=[...document.querySelectorAll('#grid .card')],seen=new Set();for(const c of cards){const h=c.querySelector('h3'),k0=key(h?.textContent||'');if(!k0||seen.has(k0)){c.remove();continue}seen.add(k0)}}
function run(){installStyle();renderTopics();renderInsights();dedupeExplore();document.documentElement.dataset.humanSignalPresentation='v14'}
window.addEventListener('load',()=>{let n=0;const t=setInterval(()=>{run();if(data().length||++n>20)clearInterval(t)},180)});
})();